<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="item_profile">

  <!-- Shared materials -->
  <material name="item_profile_natural">
    <color rgba="0.7529412 0.7529412 0.7529412 1"/>
  </material>

  <!-- Item Profile 8 40x40 light -->
  <xacro:property name="item_profile_8_40x40_light_width" value="0.04" />
  <xacro:property name="item_profile_8_40x40_light_height" value="0.04" />
  <xacro:macro name="item_profile_8_40x40_light" params="color:=natural length name">
    <link name="${name}">
      <visual>
        <geometry>
          <mesh filename="package://item_description/meshes/item/item_profile_8_40x40_light_${color}.dae"
                scale="${length} 1 1" />
        </geometry>
        <origin xyz="0 0 ${-0.5 * item_profile_8_40x40_light_height}" />
      </visual>
    </link>
  </xacro:macro>

</robot>